# Generated by Django 3.2.16 on 2024-02-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_username_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='author',
        ),
    ]
