# Generated by Django 3.2.16 on 2024-02-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_username_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_comment',
            new_name='text',
        ),
    ]
